In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler, Normalizer
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../datasets/Silver/Silver_nanoparticle_dataset_v3.csv")
df

,ID,Shape,N_Atoms,N_Bulk,N_Surface,R_min,R_max,R_diff,R_avg,R_std,...,T17,T18,T19,T20,T>20,Formation_E,EF,IP,EA,EG
0,1,Icosahedron,13,1,12,2.6303,2.8336,0.2034,2.6644,0.0791,...,0,0,0,0,0,1.074750,-3.9799,5.8119,2.7981,3.0138
1,2,Decahedron,23,1,22,2.6819,4.8235,2.1416,3.4914,0.6991,...,0,0,0,0,0,0.844232,-3.7739,5.2309,2.3148,2.9161
2,3,Decahedron,39,7,32,3.9244,4.9074,0.9831,4.3422,0.4064,...,0,0,0,0,0,0.658829,-3.4036,4.6962,2.1296,2.5666
3,4,Rhombitruncated_octahedron,43,1,42,3.0852,4.7729,1.6877,4.2044,0.7454,...,0,0,0,0,0,0.695381,-3.5300,4.7528,2.3175,2.4353
4,5,Decahedron,49,7,42,3.8637,5.9179,2.0542,4.7910,0.7647,...,0,0,0,0,0,0.593258,-3.6125,4.7698,2.4314,2.3384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,421,Tetrahedron,2925,1771,1154,14.6301,42.9301,28.3001,24.4389,6.2127,...,0,0,0,0,0,0.076392,-3.8190,4.0868,3.5513,0.5355
421,422,Decahedron,2941,2014,927,18.3836,29.2766,10.8930,22.9108,3.1656,...,0,0,0,0,0,0.033587,-3.9593,4.2549,3.6637,0.5912
422,423,Hexoctahedron,2941,2003,938,20.6732,25.3377,4.6645,22.3114,1.0700,...,0,0,0,0,0,0.039034,-3.8273,4.1297,3.5250,0.6047
423,424,Trisoctahedron,2946,2004,942,20.6179,26.7967,6.1788,22.3291,1.0373,...,0,0,0,0,0,0.040955,-3.8046,4.1063,3.5030,0.6033
424,425,Rhombitruncated_cube,2947,1927,1020,19.8160,24.4880,4.6720,22.2238,1.2691,...,0,0,0,0,0,0.046025,-3.7594,4.0600,3.4588,0.6012

In [3]:
df = df.dropna()
df

,ID,Shape,N_Atoms,N_Bulk,N_Surface,R_min,R_max,R_diff,R_avg,R_std,...,T17,T18,T19,T20,T>20,Formation_E,EF,IP,EA,EG
0,1,Icosahedron,13,1,12,2.6303,2.8336,0.2034,2.6644,0.0791,...,0,0,0,0,0,1.074750,-3.9799,5.8119,2.7981,3.0138
1,2,Decahedron,23,1,22,2.6819,4.8235,2.1416,3.4914,0.6991,...,0,0,0,0,0,0.844232,-3.7739,5.2309,2.3148,2.9161
2,3,Decahedron,39,7,32,3.9244,4.9074,0.9831,4.3422,0.4064,...,0,0,0,0,0,0.658829,-3.4036,4.6962,2.1296,2.5666
3,4,Rhombitruncated_octahedron,43,1,42,3.0852,4.7729,1.6877,4.2044,0.7454,...,0,0,0,0,0,0.695381,-3.5300,4.7528,2.3175,2.4353
4,5,Decahedron,49,7,42,3.8637,5.9179,2.0542,4.7910,0.7647,...,0,0,0,0,0,0.593258,-3.6125,4.7698,2.4314,2.3384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,421,Tetrahedron,2925,1771,1154,14.6301,42.9301,28.3001,24.4389,6.2127,...,0,0,0,0,0,0.076392,-3.8190,4.0868,3.5513,0.5355
421,422,Decahedron,2941,2014,927,18.3836,29.2766,10.8930,22.9108,3.1656,...,0,0,0,0,0,0.033587,-3.9593,4.2549,3.6637,0.5912
422,423,Hexoctahedron,2941,2003,938,20.6732,25.3377,4.6645,22.3114,1.0700,...,0,0,0,0,0,0.039034,-3.8273,4.1297,3.5250,0.6047
423,424,Trisoctahedron,2946,2004,942,20.6179,26.7967,6.1788,22.3291,1.0373,...,0,0,0,0,0,0.040955,-3.8046,4.1063,3.5030,0.6033
424,425,Rhombitruncated_cube,2947,1927,1020,19.8160,24.4880,4.6720,22.2238,1.2691,...,0,0,0,0,0,0.046025,-3.7594,4.0600,3.4588,0.6012

In [4]:
df_subset = df.drop(['ID', 'Formation_E', 'EF', 'IP', 'EA', 'EG'], axis=1)
df_subset

,Shape,N_Atoms,N_Bulk,N_Surface,R_min,R_max,R_diff,R_avg,R_std,R_skew,...,T12,T13,T14,T15,T16,T17,T18,T19,T20,T>20
0,Icosahedron,13,1,12,2.6303,2.8336,0.2034,2.6644,0.0791,2.0552,...,0,0,0,0,0,0,0,0,0,0
1,Decahedron,23,1,22,2.6819,4.8235,2.1416,3.4914,0.6991,0.6748,...,0,0,0,0,0,0,0,0,0,0
2,Decahedron,39,7,32,3.9244,4.9074,0.9831,4.3422,0.4064,0.5400,...,0,0,0,0,0,0,0,0,0,0
3,Rhombitruncated_octahedron,43,1,42,3.0852,4.7729,1.6877,4.2044,0.7454,-0.7677,...,1,0,0,0,0,0,0,0,0,0
4,Decahedron,49,7,42,3.8637,5.9179,2.0542,4.7910,0.7647,0.3264,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,Tetrahedron,2925,1771,1154,14.6301,42.9301,28.3001,24.4389,6.2127,0.6337,...,1684,87,0,0,0,0,0,0,0,0
421,Decahedron,2941,2014,927,18.3836,29.2766,10.8930,22.9108,3.1656,0.2653,...,1935,0,0,0,0,0,0,0,0,0
422,Hexoctahedron,2941,2003,938,20.6732,25.3377,4.6645,22.3114,1.0700,1.0599,...,2003,0,0,0,0,0,0,0,0,0
423,Trisoctahedron,2946,2004,942,20.6179,26.7967,6.1788,22.3291,1.0373,1.0258,...,1998,6,0,0,0,0,0,0,0,0
424,Rhombitruncated_cube,2947,1927,1020,19.8160,24.4880,4.6720,22.2238,1.2691,-0.0496,...,1927,0,0,0,0,0,0,0,0,0

In [5]:
df_subset = pd.get_dummies(df_subset)
df_subset

,N_Atoms,N_Bulk,N_Surface,R_min,R_max,R_diff,R_avg,R_std,R_skew,R_kurt,...,Shape_Tetrahedron,Shape_Tetrahexahedron,Shape_Trapezohedron,Shape_Trisoctahedron,Shape_Truncated_cube,Shape_Truncated_hexoctahedron,Shape_Truncated_octahedron,Shape_Truncated_rhombic_dodecaheron,Shape_Truncated_tetrahexahedron,Shape_Truncated_trapezohedron
0,13,1,12,2.6303,2.8336,0.2034,2.6644,0.0791,2.0552,2.6400,...,0,0,0,0,0,0,0,0,0,0
1,23,1,22,2.6819,4.8235,2.1416,3.4914,0.6991,0.6748,-0.9309,...,0,0,0,0,0,0,0,0,0,0
2,39,7,32,3.9244,4.9074,0.9831,4.3422,0.4064,0.5400,-1.4089,...,0,0,0,0,0,0,0,0,0,0
3,43,1,42,3.0852,4.7729,1.6877,4.2044,0.7454,-0.7677,-1.2828,...,0,0,0,0,0,0,0,0,0,0
4,49,7,42,3.8637,5.9179,2.0542,4.7910,0.7647,0.3264,-1.2541,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,2925,1771,1154,14.6301,42.9301,28.3001,24.4389,6.2127,0.6337,-0.1676,...,1,0,0,0,0,0,0,0,0,0
421,2941,2014,927,18.3836,29.2766,10.8930,22.9108,3.1656,0.2653,-1.0660,...,0,0,0,0,0,0,0,0,0,0
422,2941,2003,938,20.6732,25.3377,4.6645,22.3114,1.0700,1.0599,1.3460,...,0,0,0,0,0,0,0,0,0,0
423,2946,2004,942,20.6179,26.7967,6.1788,22.3291,1.0373,1.0258,1.8904,...,0,0,0,1,0,0,0,0,0,0
424,2947,1927,1020,19.8160,24.4880,4.6720,22.2238,1.2691,-0.0496,-0.9234,...,0,0,0,0,0,0,0,0,0,0

In [7]:
data = df_subset
labels_true = df[['Formation_E']]
scaler = StandardScaler()
random_seed = np.load(file="..\Seeds\seed1.npy")

for i in range(20):
    X_train, X_test, y_train, y_test = train_test_split(data, labels_true, test_size=0.2, random_state=random_seed[i])
    X_train = scaler.fit_transform(X_train.values.astype(np.float32))
    X_test = scaler.transform(X_test.values.astype(np.float32))
    
    np.save("..\datasets\Silver\\X_train" + str(i) +".npy", X_train)
    np.save("..\datasets\Silver\\X_test" + str(i) +".npy", X_test)
    np.save("..\datasets\Silver\\y_train" + str(i) +".npy", y_train)
    np.save("..\datasets\Silver\\y_test" + str(i) +".npy", y_test)

In [8]:
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np
import pandas as pd

total_test_r2 = []
total_test_mse = []

iteration = 20

seed_rf = np.load(file="..\Seeds\seed2.npy")

for iters in range(iteration):
    print("Iteration:", iters)
    name1 = "..\datasets\Silver\X_train" + str(iters) + ".npy"
    name2 = "..\datasets\Silver\X_test" + str(iters) + ".npy"
    name3 = "..\datasets\Silver\y_train" + str(iters) + ".npy"
    name4 = "..\datasets\Silver\y_test" + str(iters) + ".npy"
    
    X_train = np.load(name1, allow_pickle=True).astype(np.float32)
    print(X_train.shape)
    X_test = np.load(name2, allow_pickle=True).astype(np.float32)
    y_train = np.load(name3, allow_pickle=True).astype(np.float32).reshape(-1, 1)
    y_test = np.load(name4, allow_pickle=True).astype(np.float32).reshape(-1, 1)
    
    estimator=RandomForestRegressor(n_estimators=100, random_state=seed_rf[iters])
    estimator.fit(X_train, y_train.ravel())
    prediction_=estimator.predict(X_test)
    
    total_test_r2.append(r2_score(y_test, prediction_))
    total_test_mse.append(mean_squared_error(y_test, prediction_))

Iteration: 0
(340, 106)
Iteration: 1
(340, 106)
Iteration: 2
(340, 106)
Iteration: 3
(340, 106)
Iteration: 4
(340, 106)
Iteration: 5
(340, 106)
Iteration: 6
(340, 106)
Iteration: 7
(340, 106)
Iteration: 8
(340, 106)
Iteration: 9
(340, 106)
Iteration: 10
(340, 106)
Iteration: 11
(340, 106)
Iteration: 12
(340, 106)
Iteration: 13
(340, 106)
Iteration: 14
(340, 106)
Iteration: 15
(340, 106)
Iteration: 16
(340, 106)
Iteration: 17
(340, 106)
Iteration: 18
(340, 106)
Iteration: 19
(340, 106)

In [9]:
print("Median R2:", np.mean(np.array(total_test_r2)))
print("Median RMSE:", np.mean(np.sqrt(np.array(total_test_mse))))

Median R2: 0.9822764634303482
Median RMSE: 0.014794329051635424